# Generated by Django 3.0.2 on 2020-02-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Available to borrow'), (2, 'Borrowed by someone'), (3, 'Archived - not available anymore')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_default.jpg', upload_to='post_pics'),
        ),
    ]
